site_name: vidgts-developer
site_url: https://vidgts-developer.co.za

theme:
      name: ivory

nav:
    - Home: index.md
    - Github Commands: github_commands.md
    - Kubernetes commands: Kubernetes_commands.md
    - Azure commands: azure_commands.md
    - React commands: react_commands.md